# Generated by Django 4.2.1 on 2023-06-08 04:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManageEnterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(choices=[('V', 'Viaje'), ('D', 'Delivery'), ('O', 'Otros')], default='V', max_length=1)),
                ('departure_place_lat', models.FloatField(blank=True, null=True)),
                ('departure_place_long', models.FloatField(blank=True, null=True)),
                ('arrival_place_lat', models.FloatField(blank=True, null=True)),
                ('arrival_place_long', models.FloatField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('distance', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_state', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo')], default='B', max_length=1)),
                ('batery', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('brake_system', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suspension', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tire_1', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tire_2', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tire_3', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tire_4', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)])),
                ('cleaning', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mileage', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageEnterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageVehicles.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='plate_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageVehicles.vehicle'),
        ),
    ]
