# Generated by Django 4.2.1 on 2023-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='travel_type',
            field=models.CharField(choices=[('V', 'Vaje'), ('D', 'Delivery'), ('O', 'Otros')], default='V', max_length=1),
        ),
    ]
