# Generated by Django 4.2.1 on 2023-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0002_transaction_travel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
