# Generated by Django 4.2.1 on 2023-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0002_vehicle_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='arrival_place',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='departure_place',
        ),
        migrations.AddField(
            model_name='transaction',
            name='arrival_place_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='arrival_place_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='departure_place_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='departure_place_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
