# Generated by Django 4.2.1 on 2023-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0003_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='travel_type',
            field=models.CharField(choices=[('V', 'Viaje'), ('D', 'Delivery'), ('O', 'Otros')], default='V', max_length=1),
        ),
    ]
