# Generated by Django 4.2.1 on 2023-05-20 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0003_remove_transaction_arrival_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='oil',
            new_name='brake_system',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='suspension',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
