# Generated by Django 4.2.1 on 2023-05-20 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageVehicles', '0005_alter_vehicle_brake_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brake_system',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
