# Generated by Django 4.2.1 on 2023-05-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
