# Generated by Django 4.2.1 on 2023-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCounts', '0002_alter_wallet_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
