# Generated by Django 4.2.1 on 2023-05-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCounts', '0003_alter_person_latitud_alter_person_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
