# Generated by Django 4.2.1 on 2023-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageEnterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_desc',
            field=models.TextField(max_length=100),
        ),
    ]
